name: Enforce CODEOWNERS Approval

on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Approvals
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
