name: Enforce CODEOWNERS Approval

on:
  pull_request:
    branches:
      - main

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Approvals
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
